name: Publish Docker image

permissions:
    contents: read
    packages: write

on:
    release:
        types: [released]
    push:
      tags:
        - "*"

jobs:
    build-image:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                platform: ["linux/arm/v6", "linux/arm/v7", "linux/arm64/v8", "linux/386", "linux/ppc64le", "linux/amd64"]
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to GitHub registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push image
              run: make docker-build
              env:
                DOCKER_BUILDKIT: 1
                PLATFORM: ${{ matrix.platform }}
                IMAGE_TAG: "ghcr.io/sudo-bot/docker-rustpython/rustpython:${{ matrix.platform }}-latest"
                ACTION: push
                EXTRA_ARGS: "--cache-to=type=registry,ref=ghcr.io/sudo-bot/docker-rustpython/rustpython-buildcache,mode=max --cache-from=type=registry,ref=ghcr.io/sudo-bot/docker-rustpython/rustpython-${{ matrix.platform }}:latest"

    create-final-image:
        runs-on: ubuntu-latest
        needs: build-image
        steps:
            - name: Login to GitHub registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
                  password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
            - name: Create the manifest
              run: |
                docker manifest create docker.io/botsudo/docker-rustpython:latest \
                    ghcr.io/sudo-bot/docker-rustpython/rustpython:linux/arm/v6-latest \
                    ghcr.io/sudo-bot/docker-rustpython/rustpython:linux/arm/v7-latest \
                    ghcr.io/sudo-bot/docker-rustpython/rustpython:linux/arm/v8-latest \
                    ghcr.io/sudo-bot/docker-rustpython/rustpython:linux/386-latest \
                    ghcr.io/sudo-bot/docker-rustpython/rustpython:linux/ppc64le-latest \
                    ghcr.io/sudo-bot/docker-rustpython/rustpython:linux/amd64-latest
            - name: Push the manifest
              run: docker manifest push docker.io/botsudo/docker-rustpython:latest
            - name: Inspect the manifest
              run: docker manifest inspect docker.io/botsudo/docker-rustpython:latest
