name: Publish Docker image

permissions:
    contents: read
    packages: write

on:
    release:
        types: [released]
    push:
        tags:
            - "*"

jobs:
    build-image:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                include:
                    - { platform: "linux/arm/v6", internal-tag: "armv6" }
                    - { platform: "linux/arm/v7", internal-tag: "armv7" }
                    - { platform: "linux/arm64/v8", internal-tag: "arm64v8" }
                    - { platform: "linux/386", internal-tag: "386" }
                    - { platform: "linux/ppc64le", internal-tag: "ppc64le" }
                    - { platform: "linux/amd64", internal-tag: "amd64" }
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
            # https://github.com/docker/setup-qemu-action
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
                  password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
            - name: Build and push image
              run: make docker-build
              env:
                  DOCKER_BUILDKIT: 1
                  BUILDKIT_MULTI_PLATFORM: "false"
                  PLATFORM: ${{ matrix.platform }}
                  IMAGE_TAG: "docker.io/botsudo/docker-rustpython:${{ matrix.internal-tag }}-latest"
                  ACTION: push
                  # Disable provenance to remove the attestation from the pushed image
                  # See: https://github.com/docker/buildx/issues/1509
                  # It makes: docker.io/botsudo/docker-rustpython:<arch>-latest a manifest list
                  # And docker manifest create does not like that
                  EXTRA_ARGS: "--provenance=false"

    create-final-image:
        runs-on: ubuntu-latest
        needs: build-image
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  registry: docker.io
                  username: ${{ secrets.DOCKER_REPOSITORY_LOGIN }}
                  password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}
            - name: Create the manifest
              run: |
                  docker manifest create docker.io/botsudo/docker-rustpython:latest \
                      docker.io/botsudo/docker-rustpython:armv6-latest \
                      docker.io/botsudo/docker-rustpython:armv7-latest \
                      docker.io/botsudo/docker-rustpython:arm64v8-latest \
                      docker.io/botsudo/docker-rustpython:386-latest \
                      docker.io/botsudo/docker-rustpython:ppc64le-latest \
                      docker.io/botsudo/docker-rustpython:amd64-latest
            - name: Push the manifest
              run: docker manifest push docker.io/botsudo/docker-rustpython:latest
            - name: Inspect the manifest
              run: docker manifest inspect docker.io/botsudo/docker-rustpython:latest
